### ISSUE TITLE
Polyfill should be loaded as soon as possible

### ISSUE THREAD

**Issue by trijpstra-fourlights** [adenvt/nupolyon#32]
Hi, thanks for the plugin.

It is important to evaluate the polyfill at the earliest possible moment to ensure compatibility of the code.

This means that the plugin should insert the javascript as the first in the head tag, and execute the polyfill as soon as it's loaded.
Without that, older browsers can choke on instructions in the code that haven't been polyfilled yet.

I created a PR which converts the plugin to a nitro plugin which does exactly that.
You can use the playground to verify that the polyfill is loaded first.

**Comment by adenvt** [comment]
Great, that actually what i’m looking for.
