### ISSUE TITLE
Preload directive for polyfill script is superfluous and results in a warning in chrome

### ISSUE THREAD

**Issue by trijpstra-fourlights** [adenvt/nupolyon#44]
In https://github.com/adenvt/nupolyon/commit/f62f1f7b72f21a6adce218f7f29f428b3d3a2532 you've added a preload directive for the script.

However, since https://github.com/adenvt/nupolyon/pull/33, the script is synchronously loaded with the `nomodule` attribute. Thus, as far as I can tell, the preload link is superfluous.

This seems to be supported by the warning that Chrome is giving:

> The resource /_nupolyon/polyfill was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

I.e. chrome is saying "hey this script is never used, so why am I preloading it", which is true because the script is loaded and executed synchronously. That's also why it needs to be the first line in the <head> property, so that it's ensured that it's loaded before anything else.

So, what was the reasoning for adding the preload directive?

**Comment by adenvt** [comment]
@trijpstra-fourlights I added that because I considered about load performance , especially when we use non self-host (aka CDN). Preload can improve the load speed of script.

That why I added the preload script

**Comment by adenvt** [comment]
@trijpstra-fourlights After i review it again.

I think we should remove nomodule attribute.

nomodule make modern browser not load the polyfill when it’s support ESM. The problem is some late browser need to be load the polyfill for more latest feature.

for example, ios safari 14 is support esm, but not support Array.at (ES2022).

So what do you think?

**Comment by trijpstra-fourlights** [comment]
@adenvt I think you are correct, my apologies for including it without proper research.
I only tested it on older safari without esm support.

Perhaps we can make the `nomodule` attribute dependent on esm feature check?

So if esm supported -> preload + module
no esm supported -> only nomodule script

If you'd like I could try to make a PR

**Comment by trijpstra-fourlights** [comment]
After reading more about it, I've [created a PR](https://github.com/adenvt/nupolyon/pull/45) which should fix the behaviour.
Also, did you see my[ other PR](https://github.com/adenvt/nupolyon/pull/43)?
