### ISSUE TITLE
question: how to understand `Record<never, never>` 

### ISSUE THREAD

**Issue by dargmuesli** [adenvt/nupolyon#56]
Hey, another quick question. How does the following line define more than a string? What it `Record<never, never>`? Isn't that one `never` to much?
https://github.com/adenvt/nupolyon/blob/e3d10e2354ea190e657c0e5d84563de231850e13/src/module.ts#L12

**Comment by adenvt** [comment]
@dargmuesli That little hack for [Literal String Union Autocomplete](https://github.com/Microsoft/TypeScript/issues/29729)

In typescript, you can predefined some value using union type

```ts
type Color = 'red' | 'blue' | 'green'
```

And editor will give you autocomplete like this

<img width="530" alt="image" src="https://github.com/adenvt/nupolyon/assets/10667160/ce1a8f9c-b7f1-464a-8598-29c5ea95f40f">

But that approach doesn't allow you to use values outside defined values. You might think to change like this if you want value outside predefined values

```ts
type Color = 'red' | 'blue' | 'green' | string
```

But the editor will lost the the autocomplete

<img width="471" alt="image" src="https://github.com/adenvt/nupolyon/assets/10667160/77db75f6-c413-40e2-a4f7-7ffb1912c768">

But, if you do something like this

```ts
type Color = 'red' | 'blue' | 'green' | (string & Record<never, never>)
```

it will bring back the autocomplete

<img width="495" alt="image" src="https://github.com/adenvt/nupolyon/assets/10667160/1656e1d7-ff6b-4196-9e5e-82784470ba3a">

I hope you understand my explanation 😄

**Comment by dargmuesli** [comment]
Oh, that's very interesting, I didn't know that! Thank you very much for the great explanation! :smile:
