### ISSUE TITLE
(Error) defineNitroPlugin is not defined NUXT 3.12.2

### ISSUE THREAD

**Issue by EduardoMateos** [adenvt/nupolyon#79]
Hello,

In the latest version of Nuxt, nupolyon gives an error and does not allow the local or production environment to run.

`  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://192.168.1.128:3000/ [QR code]

  ➜ DevTools: press Shift + Option + D in the browser (v1.3.7)                                                                                                                                           9:54:56 AM

✔ Nuxt Nitro server built in 1127 ms                                                                                                                                                              nitro 9:55:01 AM

 ERROR  [worker reload] [worker init] defineNitroPlugin is not defined                                                                                                                                   9:55:02 AM

  at <anonymous> (node_modules/nupolyon/dist/runtime/server/plugins/polyfill.mjs:3:16)
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

ℹ Vite server warmed up in 9408ms                                                                                                                                                                       9:55:08 AM
ℹ Vite client warmed up in 11102ms  `

Thanks you!

**Comment by shrpne** [comment]
looks like it riles on auto-import of `defineNitroPlugin`, but in environments with `autoImport: false` it fails
